language: node_js
node_js:
- 6.9.1
addons:
  postgresql: "9.4"
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g npm@^3
before_script:
- psql -c 'create database sohtutest;' -U postgres
script:
- npm run test-cover
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
- ./deploy.sh
