language: node_js

node_js:
  - "6"

services:
  - postgresql

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g npm@^3

before_script:
  - psql -c 'create database sohtutest;' -U postgres

script:
  - npm run test-cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  skip_cleanup: true
  edge: true
  provider: elasticbeanstalk
  app:
    secure: "b1ZENZHwvvgzOhN8OzU2WoEvJ4ugSeAKWz+9MVYvlN+huNcIXMbSh0SnKzWmfgIEoc5JC69P+ESpgTIQTAIcfsLUcvxnxTW+xFX/cBvN6CF3rLWtsg5S25Qsu2OiwBlIpfhnhn+sQgdFmZG5yCqEvUW9o1luEKLbQP+Vsu/I57R1MnLht3D6JDEudOeIFR3RLFEhVA0n7YUYwQt0y3CIsZLC6hAvd4uYRICmyhBrfZihwodhJgFG2trFjV+JgF9mppS4Q1Fbv+5QxGcUb0XR/mSBFDTHBzDdQUEHn/1bNDGhQKX62DJu4mRphkWnI/E8mqH1CVBB+21yha2SQiKlGBDTDtvlQQYGL8YP0KzA44XCbEd2kHtMIElrS7BZLB3G0JBxnmJ01UaJEzd/4nFSGfOErYRHu9LDUohya831V3YGaPd/VvuBkwM17sePzG/z/bFjr+Ktf/xM1uwNRXpxqdJrgPtKqbwEDBYWJz1oCeOowx6zYGN4PvNuABxfU1iCHaVO6mia1yd9ZLUdP8KiPSoiYjMZ/15c3PRhHPLj9nWxvcoW1jp+4s6vPVfeHuRGBwy8JN4df2nFOUTRgsERNGONupslNRGBGCqgD+AQwbmWhs465jUyZaVMREPFsEGowfTutC1Sbv0Nb5KOtVa/mcsNapPdTkVphiXrVMxseec="
  env:
    secure: "FrPaCJ7AMj+8UlZUBrs0k1i/566luGrEZQexTAdIaGoRnWdUiPhxsSZ2Uetp26hIFxKhPASIqSrb0zAyuB5a/onYZX1d5uW/4nU9pJLcPaY3ZVCciDXm0SVyle+59tAJ8wFKcKIFLx14sAYbW5Pkj15UyO4JzlcP93sLUMUz9JMmr9kvrwzCBOKcTiStnvsrrk7bGmrD4MrT+fpVJZw0kbuJ3tFe0EnmwZUSAzk+z5LZ1mx/M9Ly+BF00cvj8M/bNW/JSuaJ5KvRi27C/Q1+yfRqEafqF32p0pL0liSahWBJaDOjovvC56vCcWG2+6sAi+RB+m+AqORNvJ6b+Kka0CC2Q10nzMfSM+KwFHx3E9lt2ZgwB2/pcsevFivpvsiAtFe943e+Yr4IER1Ub6vZwkODSZUwnI7A77h6xLmBgr1acWgvDZb1FgDPYvsp0zaqA2weUKMaZdCcW7mbcHPCypL4ggjnbiuo9D4ctri1eBfvt82RAqIxj4+0Na0YG/KkSmSI3GWwMu17fTZIb42vNXtzBCZslmr1jPlUTy2ViHMFpdborNbsj782lI/lenv861o3XnsAlfe3vdOUuIbDSXM11o8Upio1YRD2uZ4bw6ANC8IwyhSmBCEtD9JyXb0059oADcJfDBcUvpXfa3VxZ90ozWC105Vvx9oTPafmSmc="
  bucket_name:
    secure: "Egc3WYusZk8UMsIJGL0t/LfhfsRDpxu6+6taOSbJsmSn4t3bn9kbO/8s1pwa2ScymLipTUfAfVK3fnAO/GtuDtwia61CxVSvxuEqf09O4GvYrIyPOArhDzengWXXajJVSzCY4OBxpKHSK0zRZDfuWk8UYwW3mWJiSWR7PqkFYu3DPZ7tYNv4fc6Fq9k/ah57VG4W2QHabJlCujiiH1n7/jdrynlkwHsJNOsENplHlsowyPyXGEkrU5QxKv+oLCBAgYLyT5xRRxuR39Zksg9LlpkGn5eKuHpJIQV6nfJ4jrNEb4NPhv/i+F2aCIIh0sIFuavas98geO1vU3iuoIxWTx1/IXp5lDh3+2y0RoHfYdZ5I/GIVpzxPSVOS2O5zCvuGvztFNcNgZY3OXvd/9euulL6fomBghbQbFqI7mgsS2q5jCvriAuzOwSh/ULSABMbQSXBo2PRPPet7kulXF9XwsjahDmK536Zu3nzzeLp9ScY+MELTjFqpe1ozO9GVLDZNfhXUDHhrYVbmzqKLRaBTinwWxzQLJflqnPEN1Ni0JvmnrJOulJswCKXK8nd/XxdIi0X/6SK77ID9kw3BJAlp/RsCoKasmxBiYTWUgI1cS+cRMA0KP+T42AYV82zzyQi7K/L6JHGlr5WPDaiRue1xEi1Fz+mOPm/e41RwilSxzQ="
  region: eu-west-1
  access_key_id:
    secure: "OdXYQcvSOsVN4PmoL90iOWGiuy8v00RpGOqZzTxBTnkQU1TiJ5A33JHJr6ePgXE4avj7mF6LD4KBEqUJmGUVn63kqoZbWIjlxTYAeQWKGJot752n73n/4sJjWqLS0c7sUtDK9PcCJdZjIAAhlW9b/vVDGoFEp7eFEjDU1kRMtYJlK2EYIvzQIYpZ21E4brFpnZmDYpzDYrM4WWybZ6/vmKJdULGYbqdAFjO4hk+j4AXbDjReOYMBv//iPyPX+vu+hrBHIbjy2txZbs49H+XS4GILzYhseHSLQhLB8xnjUg+8l7RSAWJaoiavKYVvN/hc3r8De7hd7hY+sMgLxnVe4+yWr9B8I9WUsv7RikLz67YtFBE3+qFZZI+nqsebXEMFZ9Sctat/jWeN8f1sCgKbXl77oUsOHfH3OVEOF+lPWoZ3WSSa1qzwvsPqyXqLICEVDcuCgVisGiEzZQsm8IjOquGPywZvEX7xWttvXJXiHQkijBpSb9+5MCGPqQQESlZh7hMvEmPVxrClhLgKd1H3O8a7PcXFMt8fSeaWpcun1k4I/jpZCnEQVHpZb3tN6yPm/QS3XxpUascfRYXLMbfjXNbsnZ0kb+4hOizQq+MP1MucSJ++O9H8zld9M3mUJij78YKw/vTguzsnFem64nVRuGrJfjrzu8XbD46df0a80ew="
  secret_access_key:
    secure: "b9UbpCKQAecnNqLkYFbH7Gy7ydzS6xfVLZaM9h2c8s+VFxmMJxRYSnQoxBY1EoCeDRfmQFXZEV6vrdo33AMA4HuKxOMSQ8CyNhUBghn6QyBGWJY23w+oh174yzASnL3I1NMXG/69MEJ2qguilFmoELimuteh8YptK8fMBVZucHBkNS1sWI5DX2YFXxdFyqAzOi7IVIxmHpcd79WDyrr14bj63pgcjUC/0wZwpkUmUAtXQBWNTOGKh6On0lcJzGlh1ZzDE1v+SCGZ/tgrrSwBHfH1swYbolg2Hyk/b/kyHwEMSVhln26rR4B+1OUTP/to6RIHkOC7mfdy9mAe1qAt+zfA+PrGHoLWJFBu8IIWYKTusrQnQwmwNpgHl/eKEZHcEYyIBWwqFmqpmIxw/4TBytVkNtHC5wJ0iCO7x5i5fW0CJ6NddvnUwo8H4gwdZZTZvvT1XMsivDQH+PZD63jwKb6Ub3DD9q8lwusUy44+hYK39Hug/3FOqU4+ckzqWtWXRY/eXltf4GjXF2/ABRhWfnj0qujNcVeQoAWNEVrqUL6hXqlTBqNNbYBb7thVpBuqTJWmRUQCbhJWVuZHqUbKl/Nyqdg0GPTUTpTFuw52mzkS0G1UgAh1qgNUhEWeRfURqOkPJ+STYeOaZWneMnCTv3AY5Kb9S2/O9kLl+UMxgqA="
  on:
    branch: master
